
# version: 2
# updates:
  # - package-ecosystem: "nuget"
    # directory: "/bar_project1"
    # schedule:
      # interval: "daily"
  # - package-ecosystem: "nuget"
   #  directory: "/bar_project2"
    # schedule:
      # interval: "daily"
  # - package-ecosystem: "nuget"
   #  directory: "/bar_project3"
   #  schedule:
     # interval: "daily"
